import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className='flex text-white navbar bg-slate-900 p-5'>
        <div className="flex-1">
          <a href='/' className='text-3xl font-bold text-blue-100'>TypeField</a>
        </div>

        <div className="flex-none">
          <a className='link' href="/about">About</a>
        </div>
      </div>
        {children}
      </body>
    </html>
  )
}
